language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-booter' ]; then cd .. && eval "mv $currentfolder generator-booter" && cd generator-booter; fi

